# Dependencies
markdown:         kramdown
highlighter:      pygments

# Setup
title:            Douglas C. Wu
tagline:          ''
description:      'From molecular biology to computation'
url:              ""
baseurl:          ""

author:
  name:           'Douglas C. Wu'
  twitter:        'wckdouglas'
  github:         'wckdouglas'   
  gmail:          'wckdouglas'
  googleScholar:  'avA3c5MAAAAJ&hl'
  linkedin:       'wckdouglas'
  orcid:          '0000-0001-6179-3110'  

paginate:         5

include: [_pages]
