# Dependencies
markdown:         kramdown
highlighter:      pygments

# Setup
title:            Douglas C. Wu
tagline:          ''
description:      'From molecular biology to computation'
url:              ""
baseurl:          ""

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           ""

include: [_pages]
